public with sharing class PortalPasswordStrengthUsingJQuery {
    
    public String oldPassword {get; set;}
    public String newPassword {get; set;}
    public String verifyNewPassword {get; set;}        
    
    public PageReference changePassword() {
      
        return Site.changePassword(newPassword, verifyNewPassword, oldpassword);    
    }     
    
    public PortalPasswordStrengthUsingJQuery() {}

}